### ISSUE TITLE
Error connection from chromecast

### ISSUE THREAD

**Issue by Mirdinus** [kopiro/spotify-castv2-client#1]
Hey, I got an error from Spotify app on the chromecast device. I tried example multiple times with different account and I also did some editing of the code. The "crash point" is authentication from Node to device, when Node is sending access_token (SpotifyController.js:29). Can you please provide any Spotify chromecast app docs ?

Thanks in advance, 

https://github.com/kopiro/spotify-castv2-client/blob/772dfb50a6728ee27287741f596c1bac932ad8e9/SpotifyController.js#L29

**Comment by comic0** [comment]
Hi, same problem for me. I succeeded to generate a valid access token (using Spotify registered app) but when I try to connect using it, Spotify crashes on chromecast. Do you know what is the format expected for token in « creditentials » parameters ? Thanks in advance for your help.

**Comment by Mirdinus** [comment]
That problem is not in that library itself. You need a way to login to Spotify (name\pass or fb login). Spotify just do not provide the right token. Name\pass login is implemented in that library. I can provide some code for fb login (Python for now).

**Comment by kopiro** [comment]
Hi everyone, I fixed the issue.

The bug with the chrome-cast itself was this line: https://github.com/kopiro/spotify-castv2-client/commit/269ce191308ce04cebf45075ddbc591590283ffb#diff-13b1b9fef3874ba9e6c66376429f1057R27

**Comment by Mirdinus** [comment]
Nice. Thanks, I'll try it
